### ISSUE TITLE
Adding proxy configuration to the created notebooks

### ISSUE THREAD

**Issue by Barteus** [canonical/notebook-operators#208]
How to add proxy configuration to the notebook? Without this configuration notebooks git integration does not work.

**Reproduce**
1. Install Kubeflow behind the proxy (not a transparent one)
2. create a notebook
3. open notebook
4. Clone the git repository

Error when accessing the git repository.

**Workaround**
This can be fixed by manually logging into the container, stopping the notebook, adding proxy configuration and starting the ntoebook.

**Comment by Barteus** [comment]
The solution can be PodDefaults with proper configuration.

```
cat <<EOF | kubectl apply -n admin -f -
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: notebook-proxy
spec:
  desc: Add proxy settings
  env:
  - name: HTTP_PROXY
    value: <proxy-ip>
  - name: HTTPS_PROXY
    value: <proxy-ip>
  - name: NO_PROXY
    value: 127.0.0.1,localhost,local,svc, <K8s Pod range>, <K8s Svc range>, <other internal network ranges>
  selector:
    matchLabels:
      notebook-proxy: "true"
EOF
```

The key here is to add **local** and **svc** to NO_PROXY so that istio sidecar will not proxy its own traffic.
