### ISSUE TITLE
jupyter-ui: Please allow either parameterization of jupyter-ui-config-config configmap or option for controlling affinityConfig

### ISSUE THREAD

**Issue by Vultaire** [canonical/notebook-operators#245]
We have a customer which wants to customize their affinityConfig.  It seems like the charm currently creates a configmap from a static file, but doesn't offer parameterization of this configmap.

The customer is manually modifying the configmap to something like this:

```yaml
      affinityConfig:
        # If readonly, the default value will be the only option
        # value is a list of `configKey`s that we want to be selected by default
        value: "gpu-product-NVIDIA-A100-80GB-PCIe"
        # The list of available affinity configs
        # options: []
        options:
          - configKey: "gpu-product-NVIDIA-A100-80GB-PCIe"
            displayName: "nvidia.com/gpu-product"
            affinity:
             # (Require) Node having label: `node_pool=notebook-n1-standard-2`
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: "nvidia.com/gpu.product"
                          operator: "In"
                          values:
                           - "NVIDIA-A100-80GB-PCIe"
```

It would be preferable for this to be something managed by the charm rather than an unmanaged change in the environment.  Can we add functionality to allow this type of edit in some way?
