### ISSUE TITLE
Jupyter server is getting paused after one day

### ISSUE THREAD

**Issue by JyothsnaPendyala** [canonical/notebook-operators#63]
Hi!!! I have deployed kubeflow using charmhub. I could access the kubeflow dashboard and create notebook server but Jupyter notebook server is getting paused after oneday and I was not able to start it again. Is there any solution to overcome this issue?

Microk8s version : 1.22
kubeflow : V1.6

**Comment by amitk75** [comment]
This is a known issue with Kubeflow 1.6: https://github.com/kubeflow/kubeflow/issues/6648

It is fixed in 1.6.1 if you are using manifests, but not yet available in charmed kubeflow.

The workaround I am following is to patch jupyter-controller deployment every time before starting the notebook server:

```
cat <<EOF | microk8s.kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-controller
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyter-controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: jupyter-controller
        imagePullPolicy: IfNotPresent
        env:
          - name: ENABLE_CULLING
            value: "false"
EOF
```
